# Generated by Django 3.2.5 on 2022-08-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=100)),
                ('menuId', models.CharField(max_length=100)),
                ('placeId', models.CharField(max_length=100)),
                ('placeName', models.CharField(max_length=100)),
                ('merchantId', models.CharField(max_length=100)),
            ],
        ),
    ]
